### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by a624090359** [ello0211/HLPT#1]

**Comment by ello0211** [comment]
I'm sorry, could you specify which aspect you are referring to？We just discovered that the dataset has not been updated. We will upload the updates shortly. If you have any other questions, please feel free to contact me at any time.

**Comment by a624090359** [comment]
> I'm sorry, could you specify which aspect you are referring to？ If you have any questions, please feel free to contact me at any time.

peft有训练类型配置参数，配置两次只会替换掉，不能同时训练。我看代码如此，建议验证一下结果

**Comment by ello0211** [comment]
抱歉，还没来的及认真整理代码并给出注释给您造成了困扰，后续会认真整理并及时更新的。您的意思是说在finetune.py当中，同时使用lora和prefix的部分出现了问题吗？这部分应该是没有问题的，这里配置两次相当于是嵌套了两次peft_model,模型同时具有lora和prefix，如图1所示，这里的模型先获得prefix加了一层peft_model(PrefixEncoder部分)如图2，再获得lora配置，加了一层peft_model，如图3 。具体在刚开始练时（代码在peft/src/peft/peft_model.py部分）self.base_model也会迭代两次解嵌套如图4、5所示，最终达到lora和prefix的同时训练。实际上，我的代码当中还会打印出可训练的参数名称，这里分别有lora和prefix部分，如图6所示。我们也在我们的实验过程中反复验证过，这样的方法是可以对lora和prefix同时训练的。如果您还有任何问题或者不懂的地方，欢迎随时再向我提问。当然我们后续也会进一步优化我们的代码。感谢您的提问。


图1

图2


图3

图4

图5

图6
&nbsp;









顾纪豪

北京邮电大学/研究生/人工智能学院



北京




&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "ley&nbsp;kueen"; 
Date: 2023年11月28日(星期二) 上午9:59
To: "ello0211/HLPT"; 
Cc: "顾纪豪"; "Comment"; 
Subject: Re: [ello0211/HLPT] Something is wrong (Issue #1)

&nbsp;


  
I'm sorry, could you specify which aspect you are referring to？ If you have any questions, please feel free to contact me at any time.
  
peft有训练类型配置参数，配置两次只会替换掉，不能同时训练。我看代码如此，建议验证一下结果

**Comment by ello0211** [comment]
抱歉，还没来的及认真整理代码并给出注释给您造成了困扰，后续会认真整理并及时更新的。您的意思是说在finetune.py当中，同时使用lora和prefix的部分出现了问题吗？这部分应该是没有问题的，这里配置两次相当于是嵌套了两次peft_model,模型同时具有lora和prefix，如图1所示，这里的模型先获得prefix加了一层peft_model(PrefixEncoder部分)如图2，再获得lora配置，加了一层peft_model，如图3 。具体在刚开始练时（代码在peft/src/peft/peft_model.py部分）self.base_model也会迭代两次解嵌套如图4、5所示，最终达到lora和prefix的同时训练。实际上，我的代码当中还会打印出可训练的参数名称，这里分别有lora和prefix部分，如图6所示。我们也在我们的实验过程中反复验证过，这样的方法是可以对lora和prefix同时训练的。如果您还有任何问题或者不懂的地方，欢迎随时再向我提问。当然我们后续也会进一步优化我们的代码。感谢您的提问。
![图01](https://github.com/ello0211/HLPT/assets/118412731/115ee8da-9aff-4f83-b205-abde2c5ec28f)

图1
![图02](https://github.com/ello0211/HLPT/assets/118412731/d5fe518d-ee5e-4671-9d07-ff72e3e5a40c)

图2

![图03-1](https://github.com/ello0211/HLPT/assets/118412731/dc0bcf9a-1053-4313-b4bc-fcc746c65260)
![图03-2](https://github.com/ello0211/HLPT/assets/118412731/c4f22e91-155d-437b-99e9-b32a8519ff67)
图3

![图05](https://github.com/ello0211/HLPT/assets/118412731/4c8fbb16-5dc3-4765-a9f1-dcc22b104f67)

图4

![图06](https://github.com/ello0211/HLPT/assets/118412731/d9d5700a-3f5d-440f-9d64-a214428d7a94)

图5

![图04](https://github.com/ello0211/HLPT/assets/118412731/27050612-8f66-4482-a69c-78de3cf3c7ff)

图6

**Comment by a624090359** [comment]
感谢您的解答，请问您生成的adapter_config.json中，peft_type是什么？或者能否看一下生成的adapter_config.json，我想进一步对比一下解决疑惑。

**Comment by a624090359** [comment]
发现你对peft库做了大量修改，nice

**Comment by ello0211** [comment]
是的，感谢您耐心细致的阅读代码，我们确实为这份工作做出了很多努力，当然，也为注释没有完善仔细给您的阅读造成困扰感到抱歉，后续我们肯定会完善的。
对于您之前提出的问题，是这样的，在adapter_config.json中的peft_type是lora，因为Lora是训练时两层peft_model嵌套后的外层，但是同训练时一样，我们对应在进行检测时也给模型先加了一层peft_model嵌套，对应prefix部分（代码在peft/src/peft/peft_model.py处），如图1所示，使得模型可以加载训练好的prefix部分权重。同时，训练过的模型当中有着lora和prefix部分各自的权重，如图2所示为我们之前验证过的截图。我们在实验中反复验证过并确信它可以按照我们的意思运行。
再次感谢您的提问和认可！如果您还有其它任何问题，也欢迎随时提问。
![图1](https://github.com/ello0211/HLPT/assets/118412731/7b05952c-cb79-4b4f-867e-37fa3d66cf6b)
图1
![image](https://github.com/ello0211/HLPT/assets/118412731/3bad31fc-f886-417c-a597-c89884752227)
图2

**Comment by a624090359** [comment]
谢谢
